#!/bin/bash
sudo apt -y install tmux
sudo apt -y install xclip
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
cd ~
wget https://raw.githubusercontent.com/sukoto473/tmux_config/main/.tmux.conf
cd ~
tmux
echo "Tmux current prefix is CTRL+a"
echo "Press prefix+I to install the plugins and have a custom interface " 
echo "Enjoy ;)"
