#!/bin/bash
sudo apt -y install tmux
sudo apt -y install xclip
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
cd ~
git clone https://github.com/sukoto473/tmux_config/blob/main/.tmux.conf
tmux
